# Generated by Django 5.0.6 on 2024-05-27 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место привычки')),
                ('time', models.TimeField(verbose_name='время исполнения')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятности')),
                ('periodicity', models.IntegerField(default=1, verbose_name='периодичность в днях')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='награда')),
                ('expected_completion_time', models.IntegerField(verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=True, verbose_name='признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
