# Generated by Django 5.0.6 on 2024-06-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=False, verbose_name='приятная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.IntegerField(default=1, verbose_name='периодичность выполнения в днях'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(max_length=100, verbose_name='место выполнения привычки'),
        ),
    ]
