# Generated by Django 5.0.6 on 2024-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_is_pleasant_alter_habit_periodicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.SmallIntegerField(default=1, verbose_name='периодичность выполнения в днях'),
        ),
    ]
